### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by fcore117** [ryanries/SnipEx#1]
Please add option to automatically copy to clipboard, including when making notes or highligts. This is my final showstopper to replace Windows own snipping tool that will be abandoned by Microsoft and replaced by fat bloatware app. Thanks.

**Comment by ryanries** [comment]
Done. Check out the latest release: 
https://github.com/ryanries/SnipEx/releases/tag/v1.3.27

You can reopen this Issue if the feature does not meet your expectations.

**Comment by fcore117** [comment]
Thank you so much, exactly like i wanted, copies changes too like windows snipping tool. Thank you.
