### ISSUE TITLE
Freezes up after adding text

### ISSUE THREAD

**Issue by btrauma8** [ryanries/SnipEx#2]
i ran the .exe from the most recent release zip...(1.3.30.zip)
what i really really want is a snipping tool replacement that lets me add text.
it let me add text, but, then it froze up. had to kill it from task manager.

also, will there be a way to adjust font size/color of text?

**Comment by ryanries** [comment]
I agree the user experience on this could be a bit better. But I do not think SnipEx actually froze on you. I think it was waiting for you to hit Enter to "finish" the text. After typing the text, you have to "finalize it" by hitting Enter.  Also, you can change the font size, color and font face by right-clicking the Text button and choosing your preferences.  I know those things aren't the most obvious so I don't blame you. :) 

Let me know if this answers your question.

**Comment by btrauma8** [comment]
awesome. nice. i can live with that.
btw, is there a pen tool?
i see the arrow drawing thing and box making thing...which is nice, but a simple freehand pen tool would be handy.

**Comment by ryanries** [comment]
I haven't created one yet but I probably will add one in a future update. Thanks!
